### ISSUE TITLE
Garmin Authentication Failure

### ISSUE THREAD

**Issue by brentk7** [petergardfjall/garminexport#14]
Hi Peter,

I have been using your Garmin Export python script for a while (thanks for
a great utility).

When I tried downloading new runs this week I received a login error (see
below). Do you know if this is a general problem - Garmin changed something
again or is it just me having a problem?

Thanks for your help.

Regards,

Brent 

C:\Python\garminexport>garminbackup.py --backup-dir=activities --password
MyPassword --format=fit MyUserName
2017-02-04 18:46:25,911 [INFO] backing up formats: fit
2017-02-04 18:46:25,917 [INFO] authenticating user ...
2017-02-04 18:46:30,348 [ERROR] failed with exception: auth failure: unable
to extract flowExecutionKey: https://sso.garmin.com/sso/login:
<!DOCTYPE html>
<html lang="en-US">
<head>

<meta charset="utf-8" />
<meta http-equiv="Content-Type"     content="text/html; charset=utf-8" />
<meta http-equiv="X-UA-Compatible"  content="IE=edge, chrome=1" />
<meta name="viewport"               content="width=device-width,
initial-scale=1.0" />
<meta name="robots"                 content="index,follow" />
<meta name="revisit-after"          content="15 days" />
<meta http-equiv="content-language" content="en-US">
<meta name="author"                 content="Garmin International" />

<link rel="shortcut icon" href="//
connect.garmin.com/image/main/icons/favicon.ico" />

**Comment by petergardfjall** [comment]
Have you tried the latest version on `master`?
I just did a backup and no problems were encountered.
Could you be experiencing #13 (which is resolved)?

**Comment by petergardfjall** [comment]
Can neither reproduce nor get feedback from reporter. Closing ...
