### ISSUE TITLE
The server encountered an internal error () that prevented it from fulfilling this request.

### ISSUE THREAD

**Issue by pavlinux** [petergardfjall/garminexport#18]
```2017-12-30 01:32:20,456 [ERROR] failed with exception: failed to fetch activities 0 to 99 types: 500
<html><head><title>JBossWeb/2.0.0.GA - Error report</title>
<style><!--
H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px; } 
H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px; }
H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} 
BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} 
B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} 
P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}
A {color : black;}
A.name {color : black;}
HR {color : #525D76;}-->
</style>
</head><body><h1>HTTP Status 500 - </h1>
<HR size="1" noshade="noshade"><p><b>type</b> Status report</p>
<p><b>message</b> <u></u></p>
<p><b>description</b> <u>The server encountered an internal error () that prevented it from fulfilling this request.</u></p>
<HR size="1" noshade="noshade">
<h3>JBossWeb/2.0.0.GA</h3>
</body></html>
```

**Comment by petergardfjall** [comment]
Could it be a temporary server-side glitch? It worked fine for me a few moments ago.

**Comment by pavlinux** [comment]
```
2018-02-23 23:54:22,035 [DEBUG] fetching activities 0 through 99 ...
2018-02-23 23:54:23,055 [ERROR] failed with exception: failed to fetch activities 0 to 99 types: 500
<html><head><title>JBossWeb/2.0.0.GA - Error report</title><style><!--H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}A.name {color : black;}HR {color : #525D76;}--></style> </head><body><h1>HTTP Status 500 - org.springframework.beans.factory.BeanCreationException: Autowiring of fields/methods failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private com.garmin.connect.service.upload.UploadService com.garmin.mb.activity.manager.ActivityManagerBean.uploadService; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No unique bean of type [com.garmin.connect.service.upload.UploadService] is defined: Unsatisfied dependency of type [interface com.garmin.connect.service.upload.UploadService]: expected at least 1 matching bean</h1><HR size="1" noshade="noshade"><p><b>type</b> Status report</p><p><b>message</b> <u>org.springframework.beans.factory.BeanCreationException: Autowiring of fields/methods failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private com.garmin.connect.service.upload.UploadService com.garmin.mb.activity.manager.ActivityManagerBean.uploadService; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No unique bean of type [com.garmin.connect.service.upload.UploadService] is defined: Unsatisfied dependency of type [interface com.garmin.connect.service.upload.UploadService]: expected at least 1 matching bean</u></p><p><b>description</b> <u>The server encountered an internal error (org.springframework.beans.factory.BeanCreationException: Autowiring of fields/methods failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private com.garmin.connect.service.upload.UploadService com.garmin.mb.activity.manager.ActivityManagerBean.uploadService; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No unique bean of type [com.garmin.connect.service.upload.UploadService] is defined: Unsatisfied dependency of type [interface com.garmin.connect.service.upload.UploadService]: expected at least 1 matching bean) that prevented it from fulfilling this request.</u></p><HR size="1" noshade="noshade"><h3>JBossWeb/2.0.0.GA</h3></body></html>
```

**Comment by pavlinux** [comment]
2018-02-23 23:54:22,035 [DEBUG] fetching activities 0 through 99 ...
2018-02-23 23:54:23,055 [ERROR] failed with exception: failed to fetch activities 0 to 99 types: 500
<html><head><title>JBossWeb/2.0.0.GA - Error report</title><style></style> </head><body><h1>HTTP Status 500 - org.springframework.beans.factory.BeanCreationException: Autowiring of fields/methods failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private com.garmin.connect.service.upload.UploadService com.garmin.mb.activity.manager.ActivityManagerBean.uploadService; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No unique bean of type [com.garmin.connect.service.upload.UploadService] is defined: Unsatisfied dependency of type [interface com.garmin.connect.service.upload.UploadService]: expected at least 1 matching bean</h1><HR size="1" noshade="noshade"><p><b>type</b> Status report</p><p><b>message</b> <u>org.springframework.beans.factory.BeanCreationException: Autowiring of fields/methods failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private com.garmin.connect.service.upload.UploadService com.garmin.mb.activity.manager.ActivityManagerBean.uploadService; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No unique bean of type [com.garmin.connect.service.upload.UploadService] is defined: Unsatisfied dependency of type [interface com.garmin.connect.service.upload.UploadService]: expected at least 1 matching bean</u></p><p><b>description</b> <u>The server encountered an internal error (org.springframework.beans.factory.BeanCreationException: Autowiring of fields/methods failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private com.garmin.connect.service.upload.UploadService com.garmin.mb.activity.manager.ActivityManagerBean.uploadService; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No unique bean of type [com.garmin.connect.service.upload.UploadService] is defined: Unsatisfied dependency of type [interface com.garmin.connect.service.upload.UploadService]: expected at least 1 matching bean) that prevented it from fulfilling this request.</u></p><HR size="1" noshade="noshade"><h3>JBossWeb/2.0.0.GA</h3></body></html>

**Comment by pavlinux** [comment]
fixed at https://github.com/petergardfjall/garminexport/issues/21
