### ISSUE TITLE
[ERROR] failed with exception: ('Connection aborted.', error(54, 'Connection reset by peer'))

### ISSUE THREAD

**Issue by tymmej** [petergardfjall/garminexport#20]
I cannot download activities:

`./garminbackup.py --log-level=DEBUG --backup-dir=./backup tymmej@gmail.com
2018-01-28 10:40:59,914 [INFO] backing up formats: json_summary, json_details, gpx, tcx, fit
Enter password:
2018-01-28 10:41:07,869 [INFO] authenticating user ...
2018-01-28 10:41:08,782 [DEBUG] got auth response: <!DOCTYPE html>
<html class="no-js">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge;" />
        <title>Success</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="cleartype" content="on">
                <script type="text/javascript" src="/sso/js/jquery/3.1.1/jquery.min.js?20170505"></script>
            <script type="text/javascript">jQuery.noConflict();</script>
            <script type="text/javascript" src="/sso/js/json2.js"></script>
            <script type="text/javascript" src="/sso/js/consoleUtils.js?20120711"></script>
            <script type="text/javascript" src="/sso/js/postmessage.js?20120711"></script>
        
        <script type="text/javascript" src="//tags.tiqcdn.com/utag/garmin/main/prod/utag.js"></script>
                <script type="text/javascript">
                        var redirectAfterAccountLoginUrl = "";
                var consumeServiceTicket         = "true";
                var service_url                  = "https:\/\/connect.garmin.com\/modern";
                var parent_url                   = "";
            var response_url                 = "https:\/\/connect.garmin.com\/modern?ticket=ST-014852-************-cas";
                var logintoken                   = "";
                var social_uid                   = "";

                // Decode url if it's encoded unnecessarily (which is happening when SSO GAuth logins redisplay the login page due to session timeouts.)
                if (response_url.indexOf('%3A%2F%2F') != -1) {
                    response_url = decodeURIComponent(response_url);
                }
                response_url = response_url.replace(new RegExp("&amp;", 'g'),"&");

                var service_ticket = response_url.substring(response_url.indexOf('ticket=') + 7, response_url.length);

                if (redirectAfterAccountLoginUrl) {
                    consoleInfo('casEmbedSuccess.html: redirectAfterAccountLoginUrl: [' + redirectAfterAccountLoginUrl + ']');
                }
                consoleInfo('casEmbedSuccess.html: consumeServiceTicket:         [' + consumeServiceTicket + ']');
                consoleInfo('casEmbedSuccess.html: service_url:                  [' + service_url + ']');
                consoleInfo('casEmbedSuccess.html: parent_url:                   [' + parent_url + ']');
                consoleInfo('casEmbedSuccess.html: response_url:                 [' + response_url + ']');
                consoleInfo('casEmbedSuccess.html: service_ticket:               [' + service_ticket + ']');
                if (logintoken) {
                    consoleInfo('casEmbedSuccess.html: logintoken:                   [' + logintoken + ']');
                }
                if (social_uid) {
                    consoleInfo('casEmbedSuccess.html: social_uid:                   [' + social_uid + ']');
                }

                function send(msg) {
                    consoleInfo('casEmbedSuccess.html: send(): Calling XD.postMessage(msg:[' + JSON.stringify(msg) + '], target_url:[' + parent_url + '])...');
                    XD.postMessage(msg, parent_url, parent);
                    return false;
                }

                        function redirect(target){
                                var embedWidget = "";
                    if (embedWidget != 'true') {
                        if (logintoken || social_uid) {
                            //  Tell parent to close opened Gauth lite box.
                            send({'closeLiteBox':'1'});
                        } else {
                            // Tell parent to resize Gauth widget's height to just that of the loading icon.
                            send({'gauthHeight':jQuery("#GAuth-component").height()});
                        }
                    }

                                if (window.opener != null) {
                                        var iframeParent = window.opener.parent;
                                        iframeParent.location.href = target;
                                        window.close();
                                } else {
                        // If the "redirectAfterAccountLoginUrl" GAuth config parameter was specified,
                        // a full page refresh upon logon was requested, so redirect the parent window upon login.
                        if (redirectAfterAccountLoginUrl) {

                                if (embedWidget != 'true') {
                                send({'status':'SUCCESS', 'successDetails':'Login Successful'});
                                }

                            // Redirect parent of login iframe to requested service URL with ?ST=<Service Ticket ID> appended,
                            // so the webapp can validate the service ticket and log the user on to the webapp.
                            consoleInfo('casEmbedSuccess.html: Calling parent.location.href = [' + response_url + '];...');
                            top.location.href = response_url;

                            // Else if GAuth was configured not to consume the service ticket, send the service ticket and service url.
                            // It's then up to the parent page to hide the GAuth widget and validate the service ticket.
                        } else if (consumeServiceTicket == 'false') {

                            send({'status':'SUCCESS', 'successDetails':'Login Successful', 'serviceTicket':service_ticket, 'serviceUrl':service_url});

                        } else {
                        // Else consume the service ticket and log the user into the parent webapp, by making a JSONP request to the response url.
                        // This service ticket request to the parent webapp will return a small amount of JSON that we
                                        // can send in the success event to the parent page to notify them of successful logon
                                        // It's then up to the parent page to hide the GAuth widget and do whatever it wants.
                            consoleInfo('casEmbedSuccess.html: Loading ajax jsonp URL: [' + response_url + ']');
                            jQuery.ajax({
                              url: response_url,
                              dataType: 'jsonp',
                              error: function(xhr, status, error) {
                                  consoleError('casEmbedSuccess.html: Error loading ajax jsonp URL: [' + response_url + ']! Error: ' + error);
                              },
                              success: function( data, status, xhr ) {
                                consoleInfo('casEmbedSuccess.html: success loading ajax jsonp url. data: [' + data + ']');
                                  var userdata = data;
                                  if (typeof(userdata) === 'string') {
                                      userdata = JSON.parse(data);
                                  }
                                  consoleInfo('casGenericRedirect.jsp: customerId: ['             + userdata.customerId
                                                                  + '], username: ['               + userdata.username
                                                                  + '], rememberMe: ['             + userdata.rememberMe
                                                                  + '], password: ['               + userdata.password
                                                                  + '], email: ['                  + userdata.email
                                                                  + '], displayName: ['            + userdata.displayName
                                                                  + '], firstName: ['              + userdata.firstName
                                                                  + '], lastName: ['               + userdata.lastName
                                                                  + '], localePreference: ['       + userdata.localePreference
                                                                  + '], addressLine1: ['           + userdata.addressLine1
                                                                  + '], addressLine2: ['           + userdata.addressLine2
                                                                  + '], cityName: ['               + userdata.cityName
                                                                  + '], state: ['                  + userdata.state
                                                                  + '], postalCode: ['             + userdata.postalCode
                                                                  + '], country: ['                + userdata.country
                                                                  + '], passwordChangeRequired: [' + userdata.passwordChangeRequired
                                                                  + '], lastLogin: ['              + userdata.lastLogin
                                                                  + '], erpCustomerNumber: ['      + userdata.erpCustomerNumber
                                                                  + ']');
                                  send({'status'                 : 'SUCCESS',
                                        'successDetails'         : 'Login Successful',
                                        'customerId'             : userdata.customerId,
                                        'username'               : userdata.username,
                                        'rememberMe'             : userdata.rememberMe,
                                        'password'               : userdata.password,
                                        'email'                  : userdata.email,
                                        'displayName'            : userdata.displayName,
                                        'firstName'              : userdata.firstName,
                                        'lastName'               : userdata.lastName,
                                        'localePreference'       : userdata.localePreference,
                                        'addressLine1'           : userdata.addressLine1,
                                        'addressLine2'           : userdata.addressLine2,
                                        'cityName'               : userdata.cityName,
                                        'state'                  : userdata.state,
                                        'postalCode'             : userdata.postalCode,
                                        'country'                : userdata.country,
                                        'passwordChangeRequired' : userdata.passwordChangeRequired,
                                        'lastLogin'              : userdata.lastLogin,
                                        'erpCustomerNumber'      : userdata.erpCustomerNumber
                                       });
                              }
                            });
                        }
                                }
                        }
                </script>
    </head>
    <body>
            <div id="GAuth-component">
                <img src='/sso/images/ajax-loader.gif' class="loaderImage"/>
            </div>
            <script type="text/javascript">
                jQuery(document).ready(function(){
                        var service = "https:\/\/connect.garmin.com\/modern";

                    consoleInfo("casEmbedSuccess.html: ready, calling redirect('" + service + "')...");
                    redirect(service);
                });
            </script>
        </body>
</html>

2018-01-28 10:41:08,795 [DEBUG] auth ticket url: 'https://connect.garmin.com/modern?ticket=ST-014852-RkYPGCipbBTWZPxxApKk-cas'
2018-01-28 10:41:08,795 [INFO] claiming auth ticket ...
2018-01-28 10:41:14,717 [INFO] scanning activities for tymmej@gmail.com ...
2018-01-28 10:41:14,718 [DEBUG] fetching activities 0 through 99 ...
2018-01-28 10:41:32,050 [DEBUG] got 100 activities.
2018-01-28 10:41:32,058 [DEBUG] fetching activities 100 through 199 ...
2018-01-28 10:41:49,668 [DEBUG] got 100 activities.
2018-01-28 10:41:49,673 [DEBUG] fetching activities 200 through 299 ...
2018-01-28 10:42:07,029 [DEBUG] got 100 activities.
2018-01-28 10:42:07,033 [DEBUG] fetching activities 300 through 399 ...
2018-01-28 10:42:24,212 [DEBUG] got 100 activities.
2018-01-28 10:42:24,216 [DEBUG] fetching activities 400 through 499 ...
2018-01-28 10:42:40,658 [DEBUG] got 100 activities.
2018-01-28 10:42:40,663 [DEBUG] fetching activities 500 through 599 ...
2018-01-28 10:42:57,507 [DEBUG] got 100 activities.
2018-01-28 10:42:57,510 [DEBUG] fetching activities 600 through 699 ...
2018-01-28 10:43:13,848 [DEBUG] got 100 activities.
2018-01-28 10:43:13,852 [DEBUG] fetching activities 700 through 799 ...
2018-01-28 10:43:31,341 [DEBUG] got 100 activities.
2018-01-28 10:43:31,346 [DEBUG] fetching activities 800 through 899 ...
2018-01-28 10:43:50,267 [DEBUG] got 100 activities.
2018-01-28 10:43:50,271 [DEBUG] fetching activities 900 through 999 ...
2018-01-28 10:43:51,397 [DEBUG] got 4 activities.
2018-01-28 10:43:51,398 [DEBUG] fetching activities 1000 through 1099 ...
2018-01-28 10:43:54,056 [DEBUG] got 0 activities.
2018-01-28 10:43:54,057 [INFO] account has a total of 904 activities
2018-01-28 10:43:54,058 [DEBUG] 0 tried but failed activities in ./backup/.not_found
2018-01-28 10:43:54,080 [INFO] ./backup contains 0 backed up activities
2018-01-28 10:43:54,080 [INFO] activities that aren't backed up: 904
2018-01-28 10:43:54,080 [INFO] backing up activity 2404463481 from 2017-12-30 10:23:58+00:00 (1 out of 904) ...
2018-01-28 10:43:54,080 [DEBUG] getting json summary for 2404463481
2018-01-28 10:43:54,696 [DEBUG] getting json details for 2404463481
2018-01-28 10:44:01,649 [DEBUG] getting gpx for 2404463481
2018-01-28 10:47:58,950 [DEBUG] getting tcx for 2404463481
2018-01-28 10:59:00,223 [DEBUG] getting fit for 2404463481
2018-01-28 10:59:00,303 [ERROR] failed with exception: ('Connection aborted.', error(54, 'Connection reset by peer'))
2018-01-28 10:59:00,309 [ERROR] failed with exception: ('Connection aborted.', error(54, 'Connection reset by peer'))`

**Comment by pavlinux** [comment]
2018-02-23 23:34:34,461 [INFO] backing up formats: fit
2018-02-23 23:34:34,471 [INFO] authenticating user ...
2018-02-23 23:34:36,189 [INFO] claiming auth ticket ...
2018-02-23 23:34:43,217 [INFO] scanning activities for dixlor@gmail.com ...
2018-02-23 23:34:48,581 [ERROR] failed with exception: failed to fetch activities 0 to 99 types: 500
<html><head><title>JBossWeb/2.0.0.GA - Error report</title><style></style> </head><body><h1>HTTP Status 500 - </h1><HR size="1" noshade="noshade"><p><b>type</b> Status report</p><p><b>message</b> <u></u></p><p><b>description</b> <u>The server encountered an internal error () that prevented it from fulfilling this request.</u></p><HR size="1" noshade="noshade"><h3>JBossWeb/2.0.0.GA</h3></body></html>

**Comment by petergardfjall** [comment]
The latest version uses a configurable number of retries on failed download attempts. Give it a try. The Garmin Connect API appears to have been quite shaky lately.
