### ISSUE TITLE
failed with exception: {list_activities}: gave u p after 8 failed attempt(s)

### ISSUE THREAD

**Issue by spawn-github** [petergardfjall/garminexport#21]
Hi,

Sometime between Mar 21st  (last successful workout backed up) and Mar 23rd (first failed workout to back up) and all workouts since, fail to backup. I believe this is because the workouts no longer contain an "activitySummary".

It doesn't appear that I've done anything that would prevent the activitySummary from appearing in the workouts, based on an observation that the 1.1 api still presents "activitySummaryBeginTimestamp" for the same workouts that are missing activitySummary via the 1.2 api, but I'm hoping to confirm if this is a change on garmin's side, or if it's somehow an issue with my account.

Happy to provide any additional info, if it'd be useful.

Thanks!

**Comment by inginero** [comment]
2018-03-31 14:26:19,928 [INFO] claiming auth ticket ...
2018-03-31 14:26:22,086 [INFO] scanning activities for *********...
2018-03-31 14:26:22,086 [INFO] {list_activities}: attempt 1 ...
2018-03-31 14:26:22,086 [DEBUG] fetching activities 0 through 99 ...
...
2018-03-31 14:26:47,006 [INFO] {list_activities}: attempt 5 ...
2018-03-31 14:26:47,006 [DEBUG] fetching activities 0 through 99 ...
2018-03-31 14:26:49,492 [DEBUG] {list_activities}: failed: error: 'activitySummary'
2018-03-31 14:26:49,492 [INFO] {list_activities}: waiting 16 seconds for next attempt
...

**Comment by brentk7** [comment]
Also seeing this same issue.

**Comment by petergardfjall** [comment]
I'm looking into it. I think I'm onto something...

**Comment by petergardfjall** [comment]
Would you trying with the latest commit on `master`?

Appears like the old activity listing endpoint no longer works, so I switched from https://connect.garmin.com/proxy/activity-search-service-1.2/json/activities to https://connect.garmin.com/modern/proxy/activitylist-service/activities/search/activities. 

Furthermore, the old activity details json endpoint appears to have stopped working as well, so I replaced https://connect.garmin.com/modern/proxy/activity-service-1.3/json/activity_embed/<id> with https://connect.garmin.com/modern/proxy/activity-service/activity/<id>.

**Comment by inginero** [comment]
It worked great.  Thank you, Peter.  (Thanks, as well, for the extra notes on what you found.)

**Comment by pavlinux** [comment]
Hurrah, worked!!!
