### ISSUE TITLE
parser error

### ISSUE THREAD

**Issue by gatosnow** [petergardfjall/garminexport#26]
starttime =  dateutil.parser.parse(summary["activity"]["activitySummary"]["BeginTimestamp"]["value"])

**Comment by petergardfjall** [comment]
Any more detail you would like to share..?

**Comment by petergardfjall** [comment]
I figure that you ran the `get_activity.py` script, right? Please try with the latest commit (ed32d335ad4ccb17c61e957f2b1d1789a1600052). That code hadn't been updated to comply with the latest API changes (I only ever use the `garminbackup.py` script myself).
