### ISSUE TITLE
Authentication Failure

### ISSUE THREAD

**Issue by TomCasavant** [petergardfjall/garminexport#45]
I haven't used this since the Summer of last year, but it seems I'm getting authentication errors. Which may mean Garmin changed their authentication setup again.
![image](https://user-images.githubusercontent.com/7014115/75736383-0fb72a00-5ccb-11ea-8ac4-c497e61e8a50.png)

**Comment by datachico** [comment]
It's working for me.  I got the same message initially due to an incorrect password.

**Comment by TomCasavant** [comment]
Yeah, it was my fault. I didn't have the most updated version. Thanks!
