### ISSUE TITLE
GarminExport Script no longer Working

### ISSUE THREAD

**Issue by JeanDiv14** [petergardfjall/garminexport#5]
Hi Peter

Thanks for this little script.. it has ben a LIFESAVER. Unfortunately in the past few days, it is no longer working. There is a long error message, finishing off with this..

"Exception: failed to fetch activities 0 to 99 types: 403
<html><head><title>JBossWeb/2.0.0.GA - Error report</title><style></style> </head><body><h1>HTTP Status 403 - Access is denied</h1><HR size="1" noshade="noshade"><p><b>type</b> Status report</p><p><b>message</b> <u>Access is denied</u></p><p><b>description</b> <u>Access to the specified resource (Access is denied) has been forbidden.</u></p><HR size="1" noshade="noshade"><h3>JBossWeb/2.0.0.GA</h3></body></html>"

Does this mean that Garmin has shut this down..?

Ta,
Jean

**Comment by petergardfjall** [comment]
Hi Jean, I'm glad you're finding the script useful and thanks for reporting this issue.

Although I cannot say that I've seen the exact same error you've seen, I discovered that the script had stopped working for me to (however only for downloading .FIT files, all other formats were being backed up properly, when using one or more `-f` or `--format` flags).

The latest commit includes some fixes to the login procedure, which should now behave a bit more like  the one used by the Garmin Connect web application. I've successfully downloaded `.FIT` files also with this fix.

Please let me know if this addresses your problems too!

**Comment by JeanDiv14** [comment]
Hey there Peter

Apologies for the delay in getting back to you. Again.. thanks for helping to fix this, and the effort for building it in the first place! You rightly point out that I was pulling .fit files - .tcx and .gpx don't have the extra metrics (e.g. run 'ground contact time', etc), so I always pull originals and put them straight into Golden Cheetah.

So I cloned the repository again from your site (git clone) etc, ran the script and I got a different error this time:

_2016-04-16 14:05:17,331 [INFO] backing up formats: fit
2016-04-16 14:05:17,334 [INFO] authenticating user ...
2016-04-16 14:05:28,324 [ERROR] failed with exception: auth failure: unable to validate auth ticket: 500:_

It then goes into a LOT of lines of what looks like HTML code to me. I can post this, if you like..?

I hope thats helpful, and not me being silly with something.

Ta,
Jean

**Comment by petergardfjall** [comment]
Hey Jean, sorry for the delay again...
Are you still seeing the same problem?

If so, could you perhaps send me the output when running the script like so:
```
./garminbackup.py --log-level DEBUG <username/email>
```

**Comment by JeanDiv14** [comment]
Hey there Peter

I'm assuming that you made some changes to that first edit (?) because I woke up this morning after my crontab ran last night, and my new .fit files are all there! Brilliant!

Massive thanks again.. Issue resolved.

**Comment by petergardfjall** [comment]
Good to hear Jean!
I'm closing the issue.
