### ISSUE TITLE
prober hit error at byte X

### ISSUE THREAD

**Issue by GitGrezly** [petergardfjall/garminexport#55]
Downloaded cloned today the most recent version.
After upgrading i got the following error by downloading TCX files:
`2020-04-14 12:15:33,482 [DEBUG] EUC-JP Japanese prober hit error at byte 3564547
2020-04-14 12:26:41,287 [DEBUG] EUC-KR Korean prober hit error at byte 3564547`

Command i execute is:
`garmin-backup --backup-dir=activities email@em.ail --password PASSWORD --log-level DEBUG -E -f tcx
`

**Comment by petergardfjall** [comment]
I will close this for lack of activity and difficulty of reproducing.
