### ISSUE TITLE
.Fit format file download error

### ISSUE THREAD

**Issue by JeanDiv14** [petergardfjall/garminexport#6]
Hey Peter

Apologies to bother, but the Script seems to be having issues pulling .fit files again. The last successful download from GC was on 2 May.

This is the error that I got:

_

> 2016-05-08 17:44:04,035 [INFO] backing up formats: fit
> 2016-05-08 17:44:04,038 [INFO] authenticating user ...
> 2016-05-08 17:44:10,769 [INFO] retrieving activities for User@host.com ...
> 2016-05-08 17:45:08,259 [INFO] account has a total of 1575 activities.
> 2016-05-08 17:45:08,368 [INFO] /mnt/GarminConnectFiles contains 1575 backed up activities.
> 2016-05-08 17:45:08,368 [INFO] activities that aren't backed up: 0
> 2016-05-08 17:45:08,568 [INFO] backing up formats: fit
> 2016-05-08 17:45:08,572 [INFO] authenticating user ...
> 2016-05-08 17:45:25,891 [ERROR] failed with exception: ('Connection aborted.', gaierror(8, 'hostname nor servname provided, or not known'))
> Traceback (most recent call last):
>   File "/root/garminexport/./garminbackup.py", line 80, in <module>
>     with GarminClient(args.username, args.password) as client:
>   File "/root/garminexport/garminexport/garminclient.py", line 87, in __enter__
>     self.connect()
>   File "/root/garminexport/garminexport/garminclient.py", line 95, in connect
>     self._authenticate()
>   File "/root/garminexport/garminexport/garminclient.py", line 113, in _authenticate
>     self._validate_auth_ticket(validation_url)
>   File "/root/garminexport/garminexport/garminclient.py", line 178, in _validate_auth_ticket
>     response = self.session.get(redirect_url, allow_redirects=False)
>   File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 469, in get
>     return self.request('GET', url, **kwargs)
>   File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 457, in request
>     resp = self.send(prep, **send_kwargs)
>   File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 569, in send
>     r = adapter.send(request, **kwargs)
>   File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 407, in send
>     raise ConnectionError(err, request=request)
> requests.exceptions.ConnectionError: ('Connection aborted.', gaierror(8, 'hostname nor servname provided, or not known'))

_

I hope thats useful. Let me know if you need anything else.

Ta,
Jean

**Comment by petergardfjall** [comment]
Could it be a temporary glitch with the garmin site?
I just tried the script and it backed up my activities (even the .FIT files).
Maybe you could try re-running it?

**Comment by JeanDiv14** [comment]
Hey Peter

Yeah, its all fixed now. Apologies for the false alarm. It had not work for a few days. Issue closed :-)


On 09 May 2016, at 8:23 PM, Peter Gardfjäll <notifications@github.com> wrote:

Could it be a temporary glitch with the garmin site?
I just tried the script and it backed up my activities (even the .FIT files).
Maybe you could try re-running it?
