### ISSUE TITLE
Can you access detailed data per activity?

### ISSUE THREAD

**Issue by algerza** [petergardfjall/garminexport#66]
Is there any chance with this library to access all the detailed data per activity too? For example, if I'm running intervals, can I get all the stats per lap? Pace, distance, heart rate, elevation ... Thank you! @petergardfjall

**Comment by leekirk1975** [comment]
One additional request. Would it be possible to add body battery and stress detailed data get request ?

**Comment by petergardfjall** [comment]
> Is there any chance with this library to access all the detailed data per activity too? For example, if I'm running intervals, can I get all the stats per lap? Pace, distance, heart rate, elevation ... Thank you! @petergardfjall

Yes, intervals, laps etc can be found in the `.tcx` file. Go explore!

**Comment by petergardfjall** [comment]
> One additional request. Would it be possible to add body battery and stress detailed data get request ?

I have no plans on adding anything besides raw data extraction. 
I believe that any derived statistics or data processing belongs in a complementary library (which _could_ use `garminexport` to fetch activities).
