### ISSUE TITLE
Age, Weight, VO2 fields request

### ISSUE THREAD

**Issue by algerza** [petergardfjall/garminexport#67]
Hi @petergardfjall ! Amazing work, the backup works very well. Is there any change to get Age, Weight VO2 after each activity too? Thank you!

**Comment by petergardfjall** [comment]
I have no such plans at this time, sorry. I'd like to keep the library focused on activities. I suppose you could use the client from this library to write such a tool if you feel up for it.

**Comment by algerza** [comment]
Ok thanks and keep up the good work!
