### ISSUE TITLE
403 Error

### ISSUE THREAD

**Issue by JeanDiv14** [petergardfjall/garminexport#7]
Hey Peter

The script has been working flawlessly since we last spoke (some time now).. thanks for that!

This morning, I have started to get a 403 error though..

_**"HTTP Status 403 - Access is denied......Access to the specified resource (Access is denied) has been forbidden."**_

Did Garmin change something?

I'm trying to pull .fit files, if that helps.

Thanks,
Jean

**Comment by tymmej** [comment]
https://github.com/kjkjava/garmin-connect-export/issues/18#issuecomment-243859319
But I don't know how to add this in this poroject.

**Comment by petergardfjall** [comment]
Thanks for reporting and thanks @tymmej for the pointer!
Try out the most recent version of the code. By touching on `https://connect.garmin.com/legacy/session` after validating the authentication ticket, we appear to have been granted access to the API services.

Furthermore, a few the API services that were used previously had been retired and have now been updated.

Give it a shot and report back, please!

**Comment by gustavosoares** [comment]
awesome! thank you @petergardfjall for the quick fix. I was having the same 403 issue. Now it is working again.

**Comment by petergardfjall** [comment]
Thanks!
In that case I consider it fixed. Closing issue...

**Comment by tymmej** [comment]
After changing gpx URL some gpx files contains points with 0, 0 as latitude and longitude. Activity looks fine on Garmin Connect website.
Is there any parameter in URL to filter them out? I haven't this issue before.
