### ISSUE TITLE
authentication failure: 

### ISSUE THREAD

**Issue by pavlinux** [petergardfjall/garminexport#79]
$ garmin-backup --user-agent="$(ua)" -f "$FORMAT" --password "$PASS" --backup-dir="$FITS" "$LOGIN" 

2021-05-17 20:21:44,356 [INFO] backing up formats: fit
2021-05-17 20:21:44,356 [INFO] authenticating user ...
2021-05-17 20:21:44,356 [INFO] fetching CSRF token ...
2021-05-17 20:21:45,341 [ERROR] failed with exception: authentication failure: did you enter valid credentials?

**Comment by atomical** [comment]
I'm seeing this too.

**Comment by cabby26** [comment]
me too

**Comment by enydog** [comment]
https://sso.garmin.com/sso/signin problem.

**Comment by pavlinux** [comment]
https://sso.garmin.com/sso/login?service=https://connect.garmin.com/modern/&webhost=https://connect.garmin.com&gateway=true&generateExtraServiceTicket=true&generateTwoExtraServiceTickets=true

No problem

**Comment by Jetsukda** [comment]
> https://sso.garmin.com/sso/login?service=https://connect.garmin.com/modern/&webhost=https://connect.garmin.com&gateway=true&generateExtraServiceTicket=true&generateTwoExtraServiceTickets=true
> 
> No problem

Where do I need to fix it?

**Comment by enydog** [comment]
SSO with cloudflare security.
Server=cloudflare
x-frame-options=deny
CF-Cache-Status=DYNAMIC
cf-request-id=0a20b5d687000074ef948d3000000001
Expect-CT=max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
CF-RAY=65148c040efd74ef-EZE

**Comment by babbeuf** [comment]
> 
>
> SSO with cloudflare security.
> Server=cloudflare
> x-frame-options=deny
> CF-Cache-Status=DYNAMIC
> cf-request-id=0a20b5d687000074ef948d3000000001
> Expect-CT=max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
> CF-RAY=65148c040efd74ef-EZE

Are there any ways around this issue? It looks like cloudflare / Garmin are identifying automated login attempts and returning a 403 error. I've played around with different ways of making the POST request to the login url, without any luck.

**Comment by babbeuf** [comment]
> 
> 
> > SSO with cloudflare security.
> > Server=cloudflare
> > x-frame-options=deny
> > CF-Cache-Status=DYNAMIC
> > cf-request-id=0a20b5d687000074ef948d3000000001
> > Expect-CT=max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
> > CF-RAY=65148c040efd74ef-EZE
> 
> Are there any ways around this issue? It looks like cloudflare / Garmin are identifying automated login attempts and returning a 403 error. I've played around with different ways of making the POST request to the login url, without any luck.

BTW, rendering the response to the POST request in a browser results in the following Garmin-branded webpage:
![Garmin 403 Error](https://user-images.githubusercontent.com/32065946/118677449-e1374900-b7c1-11eb-918c-cf179046161b.png)

**Comment by babbeuf** [comment]
One last comment. It looks like another similar project has substituted the cloudscraper package for requests, which is working for me. Looking at the documentation for cloudscraper (https://github.com/VeNoMouS/cloudscraper), it is a package designed to bypass Cloudflare's anti-bot page.

Should be an easy fix to add cloudscraper and substitute any references to requests for that package.

**Comment by felipeam86** [comment]
> One last comment. It looks like another similar project has substituted the cloudscraper package for requests, which is working for me. Looking at the documentation for cloudscraper (https://github.com/VeNoMouS/cloudscraper), it is a package designed to bypass Cloudflare's anti-bot page.
> 
> Should be an easy fix to add cloudscraper and substitute any references to requests for that package.

I can confirm this. I have just fixed my garmin scrapping library with cloudscraper. See [this commit](https://github.com/felipeam86/garpy/commit/8409ff596f93a9ab111ee1e74dd271692660781e)

By the way, thanks for your work @petergardfjall! I had made my own library based on yours a long time a go. I'm happy to see how `garminexport` has evolved since!

**Comment by pavlinux** [comment]
a-la @felipeam86 style ))

```diff
diff -urp a/garminclient.py b/garminclient.py
--- a/garminclient.py	2021-05-19 03:35:56.396335295 +0300
+++ b/garminclient.py	2021-05-19 03:37:11.209394767 +0300
@@ -18,6 +18,7 @@ from io import BytesIO
 import dateutil
 import dateutil.parser
 import requests
+import cloudscraper
 
 from garminexport.retryer import Retryer, ExponentialBackoffDelayStrategy, MaxRetriesStopStrategy
 
@@ -110,7 +111,7 @@ class GarminClient(object):
         self.disconnect()
 
     def connect(self):
-        self.session = requests.Session()
+        self.session = cloudscraper.create_scraper()
         self._authenticate()
 
     def disconnect(self):

```

**Comment by micky-gee** [comment]
Great; this cloudscraper fix works.

**Comment by jacobhell** [comment]
Thanks @pavlinux , I created #80 based on your changes.

**Comment by pavlinux** [comment]
Аgain [ERROR] failed with exception: authentication failure: did you enter valid credentials?

**Comment by pavlinux** [comment]
Huh, funny, after I enter to  my profile via https://connect.garmin.com/ they work again :)

 
![aaa](https://user-images.githubusercontent.com/1057453/119270083-aee37c80-bc03-11eb-9d00-bc6bcdccc7be.png)

**Comment by jacobhell** [comment]
@pavlinux it is still working for me

```
PS C:\projects\personal\jacobhell.github.io> garmin-backup fake_email --password fake_password
2021-05-23 13:36:02,058 [INFO] backing up formats: json_summary, json_details, gpx, tcx, fit
2021-05-23 13:36:02,203 [INFO] authenticating user ...
2021-05-23 13:36:02,204 [INFO] fetching CSRF token ...
2021-05-23 13:36:03,874 [INFO] claiming auth ticket ...
2021-05-23 13:36:06,131 [INFO] scanning activities for fake_email ...
2021-05-23 13:36:06,131 [INFO] {list_activities}: attempt 1 ...
2021-05-23 13:36:08,918 [INFO] account has a total of 585 activities
2021-05-23 13:36:09,033 [INFO] .\activities contains 582 backed up activities
2021-05-23 13:36:09,033 [INFO] activities that aren't backed up: 3
2021-05-23 13:36:09,035 [INFO] backing up activity 6824592079 from 2021-05-22 18:32:02+00:00 (1 out of 3) ...
2021-05-23 13:36:09,040 [INFO] {get_activity_summary}: attempt 1 ...
2021-05-23 13:36:09,206 [INFO] {get_activity_details}: attempt 1 ...
2021-05-23 13:36:09,474 [INFO] {get_activity_gpx}: attempt 1 ...
2021-05-23 13:36:10,174 [INFO] {get_activity_tcx}: attempt 1 ...
2021-05-23 13:36:11,371 [INFO] {get_activity_fit}: attempt 1 ...
2021-05-23 13:36:11,763 [INFO] backing up activity 6829167314 from 2021-05-23 13:42:52+00:00 (2 out of 3) ...
2021-05-23 13:36:11,764 [INFO] {get_activity_summary}: attempt 1 ...
2021-05-23 13:36:11,960 [INFO] {get_activity_details}: attempt 1 ...
2021-05-23 13:36:12,325 [INFO] {get_activity_gpx}: attempt 1 ...
2021-05-23 13:36:12,837 [INFO] {get_activity_tcx}: attempt 1 ...
2021-05-23 13:36:13,576 [INFO] {get_activity_fit}: attempt 1 ...
```

**Comment by oiramkawon** [comment]
I have the authentication error too at the moment...

**Comment by peemot** [comment]
I too have this authentication error.
Strange thing is.. it worked yesterday. I downloaded about 100 workouts. But few hours later it did not let me in anymore.
Is there some kind of cloudflare banning system or something?
Is there a simple way to get a more detailed error log?

Anyway.. i tried some cloudscraper parameters and once again i got in (maybe temporarily). At the moment this change worked:

`    def connect(self):
        self.session = cloudscraper.create_scraper(
            browser={
            'browser': 'firefox',
            'platform': 'windows',
            'mobile': False
        }
    )`

**Comment by bobgott** [comment]
@peemot , I too was having problems getting in yesterday and today.  I added the cloudscraper parameters as you have above and now it works (of course, who knows for how long).

thank you.

**Comment by petergardfjall** [comment]
Sorry for not responding earlier to this. I managed to download all my activities just now on `0.4.0` (that is without `cloudscraper` or any code modifications). Maybe Garmin chose to disable their CloudFlare bot protection scheme? Would anyone else care to try out `0.4.0`?

**Comment by davosian** [comment]
@petergardfjall I just tried again with the following steps, but I am still having the same issue (out of Switzerland):

```sh
source env/bin/activate
(env)

pip install garminexport                                                                                                                    [13:07:20]
Requirement already satisfied: garminexport in ./env/lib/python3.9/site-packages (0.4.0)
Requirement already satisfied: requests<3,>=2.0 in ./env/lib/python3.9/site-packages (from garminexport) (2.25.1)
Requirement already satisfied: python-dateutil~=2.4 in ./env/lib/python3.9/site-packages (from garminexport) (2.8.1)
Requirement already satisfied: six>=1.5 in ./env/lib/python3.9/site-packages (from python-dateutil~=2.4->garminexport) (1.16.0)
Requirement already satisfied: certifi>=2017.4.17 in ./env/lib/python3.9/site-packages (from requests<3,>=2.0->garminexport) (2021.5.30)
Requirement already satisfied: idna<3,>=2.5 in ./env/lib/python3.9/site-packages (from requests<3,>=2.0->garminexport) (2.10)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in ./env/lib/python3.9/site-packages (from requests<3,>=2.0->garminexport) (1.26.5)
Requirement already satisfied: chardet<5,>=3.0.2 in ./env/lib/python3.9/site-packages (from requests<3,>=2.0->garminexport) (4.0.0)
(env)

garmin-backup --backup-dir=activities me@mail.com                                                                                        [13:08:08]
2021-07-30 13:08:09,568 [INFO] backing up formats: json_summary, json_details, gpx, tcx, fit
Enter password: 
2021-07-30 13:08:25,221 [INFO] authenticating user ...
2021-07-30 13:08:25,221 [INFO] fetching CSRF token ...
2021-07-30 13:08:25,556 [ERROR] failed with exception: authentication failure: did you enter valid credentials?
>>> elapsed time 17s
```

**Comment by petergardfjall** [comment]
> @petergardfjall I just tried again with the following steps, but I am still having the same issue (out of Switzerland):

Thanks @davosian. And you're _sure_ you are using the right credentials? ;-)
Strangely enough I cannot reproduce the error. I've tried running it several times and I'm not having login issues. :confused: 

Could you please try `garmin-backup --password=<secret> --log-level=DEBUG <mail>` to get some more details?

**Comment by davosian** [comment]
A actually copied the password from my password manager, but just in case I have now changed it to be simpler without special characters to make sure this is not tripping things up. Here is the debugging output I get even with the simplified password entered directly on the command line:

```
2021-07-30 22:55:32,176 [INFO] backing up formats: json_summary, json_details, gpx, tcx, fit
2021-07-30 22:55:32,176 [INFO] authenticating user ...
2021-07-30 22:55:32,176 [INFO] fetching CSRF token ...
2021-07-30 22:55:32,185 [DEBUG] Starting new HTTPS connection (1): sso.garmin.com:443
2021-07-30 22:55:32,402 [DEBUG] https://sso.garmin.com:443 "GET /sso/login?service=https%3A%2F%2Fconnect.garmin.com%2Fmodern%2F&gauthHost=https%3A%2F%2Fsso.garmin.com%2Fsso HTTP/1.1" 200 None
2021-07-30 22:55:32,447 [DEBUG] https://sso.garmin.com:443 "POST /sso/signin?service=https%3A%2F%2Fconnect.garmin.com%2Fmodern%2F&gauthHost=https%3A%2F%2Fsso.garmin.com%2Fsso HTTP/1.1" 403 None
2021-07-30 22:55:32,461 [DEBUG] got auth response: <html lang="en-US" class="no-js" xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <meta charset="utf-8" />
  <title>Garmin: Maintenance</title>
  <style>...</style>
  <style type="text/css">...</style>
</head>
<body>

  
  <main class="app" id="app">
    <div class="app__content">
      <div class="app__error-description">
        <a class="app__logo" data-ua-event="Global Header, Logo, Logo Link">
          <svg class="gh__logo__svg" viewBox="0 0 786 113" xmlns="http://www.w3.org/2000/svg" fill-rule="evenodd" clip-rule="evenodd" stroke-linejoin="round" stroke-miterlimit="1.414"><title>Garmin</title>...</path></svg>
        </a>

        <h1 class="app__heading">We’re sorry.</h1>
        <p class="app__subheading">Something went wrong, and our site is temporarily unavailable.<br />We’re already working to get things back on course.</h2>

        <div class="app__error__details">
          <div class="cf-error-details cf-error-1020">
  <h1>Access denied</h1>
  <p>This website is using a security service to protect itself from online attacks.</p>
  <ul class="cferror_details">
    <li>Ray ID: 67717d0c9d640204</li>
    <li>Timestamp: 2021-07-30 20:55:32 UTC</li>
    <li>Your IP address: 144.2.119.210</li>
    <li class="XXX_no_wrap_overflow_hidden">Requested URL: sso.garmin.com/sso/signin?service=https%3A%2F%2Fconnect.garmin.com%2Fmodern%2F&amp;gauthHost=https%3A%2F%2Fsso.garmin.com%2Fsso </li>
    <li>Error reference number: 1020</li>
    <li>Server ID: FL_64F52</li>
    <li>User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36</li>
  </ul>
</div>

        </div>
      </div>
    </div>
  </main>
  
</body>
</html>
2021-07-30 22:55:32,464 [ERROR] failed with exception: authentication failure: did you enter valid credentials?
```

I have not tried any of the suggested fixes (mainly because I do not understand how to apply them), but I could certainly do so if this helps if someone can give me more detailed instructions on how to apply the patch.

**Comment by davosian** [comment]
Update: I got it to work using cloudscraper:

I installed the library with `pip install cloudscraper`. Then I manually applied the patch from @pavlinux: https://github.com/petergardfjall/garminexport/issues/79#issuecomment-843658546

**Comment by davosian** [comment]
Looks I am experiencing exactly the same as others in this thread: this morning, the fix I used was still working fine, this afternoon, I ran into the same problem again. After applying the following modification from https://github.com/petergardfjall/garminexport/issues/79#issuecomment-885457637, I am back in business:

```python
self.session = cloudscraper.create_scraper(
            browser = {
                'browser': 'firefox',
                'platform': 'windows',
                'mobile': False
            }
        )
```

**Comment by andreloeffelmann** [comment]
Had the same authentication issues. But I can confirm that the fix from #79 including the `browser` specification object is working. Just tried it out from germany.

**Comment by davosian** [comment]
May I ask why this got closed? The proposed solution did not get merged, right?

**Comment by pavlinux** [comment]
> May I ask why this got closed? The proposed solution did not get merged, right?
```
while
    garmin-backup --user-agent="$(ua -o win)" -f ${FORMAT} --password "${PASS}" --backup-dir="$FITS" "$LOGIN";
ret=$?
[ $ret -ne 0 ]; do :; done;
```

**Comment by micky-gee** [comment]
@pavlinux,

You've got a bunch of folks submitting good PRs that solve these problems, but you'd rather make users run this "n-times" expecting "n-1" failures in a hacked bash script.

I don't get it.  Can you help me understand?

**Comment by petergardfjall** [comment]
@pavlinux you initially proposed the use of `cloudscraper` if I remember correctly (later a PR was submitted: https://github.com/petergardfjall/garminexport/pull/80). Did you experience issues with that fix (some comments seem to indicate that that fix can be a little "hit-and-miss prone")? What lead you to go back to retries like in https://github.com/petergardfjall/garminexport/issues/79#issuecomment-890557188?

**Comment by atomical** [comment]
Any updates?

**Comment by petergardfjall** [comment]
I still cannot reproduce the issue locally. Downloads/backups work as expected.

**Comment by pavlinux** [comment]
> @pavlinux,`cloudscraper` если я правильно помню, вы изначально предлагали использовать его (позже был отправлен PR: [# 80](https://github.com/petergardfjall/garminexport/pull/80) ). Возникли ли у вас проблемы с этим исправлением (некоторые комментарии, кажется, указывают на то, что это исправление может быть несколько "случайным")? Что заставило вас вернуться к повторным попыткам, как в [# 79 (комментарий)](https://github.com/petergardfjall/garminexport/issues/79#issuecomment-890557188) ?

The error occurs if you do not go to the connect.garmin.com site for a long time (~ 3+ days) or through Garmin Express.

Now I have such a diff: 

```
diff -urp garminexport/backup.py /usr/local/lib/python3.7/dist-packages/garminexport/backup.py
--- garminexport/backup.py	2021-11-25 12:53:16.904856931 +0300
+++ /usr/local/lib/python3.7/dist-packages/garminexport/backup.py	2021-05-09 13:45:28.543939957 +0300
@@ -47,7 +47,7 @@ def export_filename(activity, export_for
         id=activity[0],
         time=activity[1].isoformat(),
         suffix=format_suffix[export_format])
-    return fn.replace(':', '_') if os.name == 'nt' else fn
+    return fn.replace(':', '_')
 
 
 def need_backup(activities, backup_dir, export_formats=None):
Только в /usr/local/lib/python3.7/dist-packages/garminexport/cli: __pycache__
diff -urp garminexport/garminclient.py /usr/local/lib/python3.7/dist-packages/garminexport/garminclient.py
--- garminexport/garminclient.py	2021-11-25 12:53:16.906856906 +0300
+++ /usr/local/lib/python3.7/dist-packages/garminexport/garminclient.py	2021-05-20 03:03:48.104951402 +0300
@@ -18,6 +18,7 @@ from io import BytesIO
 import dateutil
 import dateutil.parser
 import requests
+import cloudscraper
 
 from garminexport.retryer import Retryer, ExponentialBackoffDelayStrategy, MaxRetriesStopStrategy
 
@@ -110,7 +111,7 @@ class GarminClient(object):
         self.disconnect()
 
     def connect(self):
-        self.session = requests.Session()
+        self.session = cloudscraper.create_scraper()
         self._authenticate()
 
     def disconnect(self):
@@ -128,6 +129,7 @@ class GarminClient(object):
             "_csrf": self._get_csrf_token(),
         }
         headers = {
+            'Content-Encoding': 'deflate, gzip',
             'origin': 'https://sso.garmin.com',
         }
         if self._user_agent_fn:
```

**Comment by plandes** [comment]
The diff @pavlinux contributed fixed the (reoccurring) issue for me.  Would be great if the authors could fold it in as I have switched to using this project as a dependency giving up trying to maintain these issues myself.  Ideally, all such programs that programmatically talk to Garmin connect would centralize around one very basic library (much like this).

**Comment by petergardfjall** [comment]
The most recent version of `garminexport` (`0.4.1`) can optionally be installed with support for circumventing Cloudflare's bot challenges like so:

```bash
pip install garminexport[cloudflare]
```

**Comment by plandes** [comment]
@petergardfjall 

I wish I could tell you.  I'm still moving things around to get it to work more consistently.  It isn't determinist in the least and sometimes it works on the first try.  Other times, I have to even stop the process and restart it a few times.

I did try  `garminexport[cloudflare]` and it fails just as often, so I'd need to test more with it.
