### ISSUE TITLE
authentication failure ( same problem  ) 

### ISSUE THREAD

**Issue by nestore** [petergardfjall/garminexport#84]
I have an authentication failure  using right credentials. the behavior is the same already described in the other two issue like this one 
the response from garmin is 

We’re sorry.

Something went wrong, and our site is temporarily unavailable.
We’re already working to get things back on course.
Access denied

This website is using a security service to protect itself from online attacks.

    Ray ID: 6c01653fcfe059ef
    Timestamp: 2021-12-19 14:42:05 UTC
    Your IP address: 87.13.39.4
    Requested URL: sso.garmin.com/sso/signin?gauthHost=https%3A%2F%2Fsso.garmin.com%2Fsso&service=https%3A%2F%2Fconnect.garmin.com%2Fmodern%2F
    Error reference number: 1020
    Server ID: FL_270F52
    User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36

tried with the last version  and changhing randomly the User-Agent

**Comment by petergardfjall** [comment]
Probably due to Cloudflare's anti-bot protection which appears to impact only some users.

The most recent version of `garminexport` (`0.4.1`) can be installed with support for circumventing Cloudflare's bot challenges like so:

```bash
pip install garminexport[cloudflare]
```
