### ISSUE TITLE
Problem with authentication

### ISSUE THREAD

**Issue by ilsalgo** [petergardfjall/garminexport#87]
Hi, the plug-in doesn't work again, i guess it depends on Garmin who introduced two factor authentication, in fact when i try to backup i get an authentication error and immediately also the sms with the verification code.

**Comment by mmagnus** [comment]
OK, so it's not only me, I have the same problem.

**Comment by rickbhs** [comment]
i have the same problem

**Comment by lakemike** [comment]
same for me

**Comment by jensbusch** [comment]
Anyone any solution here? I got the same issue

**Comment by 62north** [comment]
For me auth only works if session_factory is set to cloudscraper.create_scraper and this is only used if cloudscraper is installed (otherwise it defaults to requests.session). Thus I had to pip3 install cloudscraper first.

**Comment by rickbhs** [comment]
that worked also for me

**Comment by ilsalgo** [comment]
> For me auth only works if session_factory is set to cloudscraper.create_scraper and this is only set if cloudscraper is installed (otherwise it defaults to requests.session which does not work). Thus I had to pip3 install cloudscraper first.

not work for me

**Comment by ilsalgo** [comment]
no, the problem is the two factor authentication. When I try to connect to my accont, Garmin send a passcode via sms for second authorization (this is necessary for use some services). In this case, I receive the sms but is not possible use the code in Garmin Export.

**Comment by petergardfjall** [comment]
This library does not support two-factor authentication. I have no intention of adding support at this time.
